NumPy - Numerical Python

Advantages of NumPy Arrays:
1.   Allows several Mathematiccal Operations
2.   Faster Operations

In [1]:
import numpy as np

List vs Numpy Time Comparis

In [2]:
from time import perf_counter

Time taken by List

In [3]:
python_list = [i for i in range(10000)]

start_time = perf_counter()

python_list = [i+5 for i in python_list]

end_time = perf_counter()

print(end_time-start_time)

0.0007311719999734123


Time taken by Numpy

In [4]:
np_array = np.array([i for i in range(10000)])

start_time = perf_counter()

np_array += 5

end_time = perf_counter()

print(end_time-start_time)

0.00016672699996433948


Numpy Arrays

In [5]:
# List
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [6]:
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [7]:
# Creating a 1 1-dimensional array
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [8]:
a.shape

(6,)

In [9]:
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
b.shape

(2, 3)

In [11]:
c = np.array([(1,2,3,4,5),(6,7,8,9,10)],dtype=float)
print(c)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


Inital Placeholders in numpy arrays

In [12]:
# create a numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix
i = np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# create a numpy array with random values
r = np.random.random((3,4))
print(r)

[[0.97307548 0.9550838  0.6318344  0.82253187]
 [0.29077867 0.19652479 0.04744708 0.6758228 ]
 [0.43166007 0.29070767 0.66615135 0.56754252]]


In [17]:
# create integer values array within a specific range
ran = np.random.randint(10,100,(3,4))
print(ran)

[[25 85 18 25]
 [37 12 48 14]
 [58 38 14 29]]


In [18]:
# array with evenly spaced values
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,30,40]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

Analysing a numpy array

In [21]:
c = np.random.randint(10,90,(5,5))
print(c)

[[38 67 25 22 63]
 [31 15 50 77 76]
 [53 35 55 64 11]
 [59 73 21 86 19]
 [59 87 58 58 13]]


In [22]:
# array dimension
print(c.shape)

(5, 5)


In [23]:
# number of dimension
print(c.ndim)

2


In [24]:
# number of elements in an array
print(c.size)

25


In [25]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on an np array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9]

print(list1+list2) #concatenate of joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [28]:
print(a)
print(b)

[[1 0 2]
 [8 5 0]
 [9 6 9]]
[[16 15 10]
 [11 13 10]
 [19 14 17]]


In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[17 15 12]
 [19 18 10]
 [28 20 26]]
[[-15 -15  -8]
 [ -3  -8 -10]
 [-10  -8  -8]]
[[ 16   0  20]
 [ 88  65   0]
 [171  84 153]]
[[0.0625     0.         0.2       ]
 [0.72727273 0.38461538 0.        ]
 [0.47368421 0.42857143 0.52941176]]


In [30]:
print(np.add(a,b))

[[17 15 12]
 [19 18 10]
 [28 20 26]]


In [31]:
print(np.subtract(a,b))

[[-15 -15  -8]
 [ -3  -8 -10]
 [-10  -8  -8]]


In [32]:
print(np.multiply(a,b))

[[ 16   0  20]
 [ 88  65   0]
 [171  84 153]]


In [33]:
print(np.divide(a,b))

[[0.0625     0.         0.2       ]
 [0.72727273 0.38461538 0.        ]
 [0.47368421 0.42857143 0.52941176]]


Array Manipulation

In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 4 4]
 [9 4 6]]
(2, 3)


In [35]:
#Transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 9]
 [4 4]
 [4 6]]
(3, 2)


In [36]:
array = np.random.randint(20,30,(4,5))
print(array)
print(array.shape)

[[27 24 22 24 23]
 [25 28 20 24 29]
 [26 24 29 28 28]
 [26 22 21 27 29]]
(4, 5)


In [37]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[27 25 26 26]
 [24 28 24 22]
 [22 20 29 21]
 [24 24 28 27]
 [23 29 28 29]]
(5, 4)


In [38]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 8 2]
 [2 9 0]]
(2, 3)


In [39]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 8]
 [2 2]
 [9 0]]
(3, 2)
